S2 us3 feature homepage
WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game pull request #16
Opened 2023-11-12 18:29 UTC by Jojopok

2023-11-14 13:16 UTC, WilliamTahar requested changes

2023-11-14 13:16 UTC, WilliamTahar commented on src/View/Home/login.html.twig
> +            <button type="" class="creatAccount" formaction="inscription">Créer un compte</button>
A quoi sert l'attribut **type** ?

2023-11-14 13:16 UTC, WilliamTahar commented on src/View/Home/login.html.twig
> +            <button type="" class="creatAccount" formaction="inscription">Créer un compte</button>
Egalement, qu'est-ce que l'attribut **formaction** ?

2023-11-14 13:16 UTC, WilliamTahar commented on src/View/Home/navbar.html.twig
> +    <script src="assets/js/navbar.js" defer></script>
Pourquoi importé le JavaScript ici ? 
Ça place est dans le **layout**

2023-11-14 13:16 UTC, WilliamTahar commented on src/routes.php
>      'scene' => ['SceneController', 'scene', ['id'], 'planEnigme', ['id']],
Ce n'est pas comme ça qu'on implémente les paramètres

2023-11-14 14:49 UTC, Jojopok commented on src/View/Home/login.html.twig
> +            <button type="" class="creatAccount" formaction="inscription">Créer un compte</button>
A rien effectivement, j'ai corrigé.

2023-11-14 14:49 UTC, Jojopok commented on src/View/Home/navbar.html.twig
> +    <script src="assets/js/navbar.js" defer></script>
Modifié.

2023-11-14 14:49 UTC, Jojopok commented on src/routes.php
>      'scene' => ['SceneController', 'scene', ['id'], 'planEnigme', ['id']],
Modifié.

2023-11-14 14:50 UTC, Melprcllr approved these changes
goooooood

2023-11-14 14:51 UTC, Didixe approved these changes
it's ok

2023-11-15 10:12 UTC, WilliamTahar approved these changes

2023-11-15 10:13 UTC, WilliamTahar commented
@Jojopok Il faut corriger les conflits avant de pouvoir **merge**

2023-11-15 10:27 UTC, Melprcllr approved these changes

2023-11-15 10:30 UTC, merged